### ISSUE TITLE
Force graph does not display when center is added

### ISSUE THREAD

**Issue by ghost** [ayasdi/grapher-center#1]
I'm not sure why this happens, however if you add center to the force graph example, the graph does not display.  Perhaps it has something to do with the fact that the force algorithm has not settled the nodes before center is fired?

Incidentally, I'm trying to achieve this scenario:
1. Force graph settels the layout of all nodes
2. graph is zoomed out to fit entire graph in visible viewport
3. graph is centered

**Comment by cixzhang** [comment]
Seems like what happens is that in the force example, we pass in data as part of the initialization in grapher which is where we're also calculating the center. However the canvas doesn't yet exist. This is probably wrong. We should be calculating the transformation on render if no other transformations have been applied.

By default, this center module should display a centered graph on first render. If you need to center the graph again afterwards, you can call center directly:

```
var grapher = new Grapher(...);
// ...
grapher.center();
```

For the case where the graph needs to be centered after force settles, if d3.force is used you can do something like this:

```
var force = d3.layout.force()....

force.on('end', function () {
  grapher.center();
});
```

I'll push a fix so the graph should appear on first render. Hope this helps!

**Comment by cixzhang** [comment]
Should be fixed!

**Comment by ghost** [comment]
@cixzhang Great, thanks!
